set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle/'

Bundle 'scrooloose/syntastic'
Bundle 'scrooloose/nerdtree'
Bundle 'kien/ctrlp.vim'
Bundle 'mileszs/ack.vim'
Bundle 'ervandew/supertab'
Bundle 'airblade/vim-rooter'
Bundle 'Lokaltog/vim-powerline'
Bundle 'Raimondi/delimitMate'
Bundle 'jistr/vim-nerdtree-tabs'

set number
set ts=2
set smarttab
set expandtab
set shiftwidth=2
set autoindent
set showmatch
set smartcase
set hlsearch
set incsearch
set mouse=a
syntax on

set t_Co=256
set colorcolumn=80
set guifont=Inconsolata:h16

colorscheme Monokai

filetype plugin indent on

let g:syntastic_enable_signs=1
let g:syntastic_auto_loc_list=1
let g:syntastic_disabled_filetypes = ['html']

set backspace=indent,eol,start
